./tricount -f /graph_data/csr_graph/livej        0 1
./tricount -f /graph_data/csr_graph/orkut        0 1
./tricount -f /graph_data/csr_graph/twitter20    0 1
./tricount -f /graph_data/csr_graph/twitter_rv   0 1
./tricount -f /graph_data/csr_graph/friendster   0 1
./tricount -f /graph_data/csr_graph/s20.kron     0 1
./tricount -f /graph_data/csr_graph/s21.kron     0 1
./tricount -f /graph_data/csr_graph/s22.kron     0 1
./tricount -f /graph_data/csr_graph/s23.kron     0 1
./tricount -f /graph_data/csr_graph/s24.kron     0 1
./tricount -f /graph_data/csr_graph/s25.kron     0 1
